select * from customer_satisfaction.customer;

-- Total revenu generated by male vs female customers
select gender, SUM(purchase_amount) as revenue
from customer_satisfaction.customer 
group by gender;

-- Which customer used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer_satisfaction.customer 
where discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) from customer_satisfaction.customer);

-- Top 5 products with the highest average review rating - used as marketing and sell with premium price
select item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer_satisfaction.customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average Purchase Amounts bweteen Standard and Express Shipping - for fast delivery to customers
select shipping_type,
AVG(purchase_amount)
from customer_satisfaction.customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Do subsribe customers spend more? Compare average spend and total revenue between subscribers and non-subscribers;
select subscription_status,COUNT(customer_id) as total_customers, 
ROUND(AVG(purchase_amount)) as avg_spend,
ROUND(SUM(purchase_amount)) as total_revenue
from customer_satisfaction.customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Which 5 products have the highest percentage of purchases with discount applied? - discount rate per product - which products relay heavily on discounts to sell products
select item_purchased, ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer_satisfaction.customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Segement customers into New, Returning, and Loyal based on there total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New' 
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_satisfaction.customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- 3 Most purchasing products within each category - rank, and dense rank - put sunglasses and belt keep 2 because it has same numbers, so row_number
with item_counts as (
SELECT category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(Partition by category order by count(customer_id)DESC) as item_rank
from customer_satisfaction.customer
group by category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Are customers who are repeat buyers - more than 5 previous purchases also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_satisfaction.customer
where previous_purchases > 5
group by subscription_status; 

-- What is the revenue contribution of each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;